# -*- coding: utf-8 -*-
"""Protien_Sequence_Transformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1izcpi8kT_9ACb_eX1JyjMnFGuQzTQZrt
"""

!pip -q install torch requests numpy matplotlib tqdm certifi urllib3

from __future__ import annotations

import importlib.util
import os
import subprocess
import sys

if os.name != "nt":
    os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")


def ensure_dependencies() -> None:
    packages = {
        "torch": "torch",
        "requests": "requests",
        "numpy": "numpy",
        "matplotlib": "matplotlib",
        "tqdm": "tqdm",
        "certifi": "certifi",
        "urllib3": "urllib3",
    }
    missing = [pkg for module, pkg in packages.items() if importlib.util.find_spec(module) is None]
    if not missing:
        return

    cmd_text = "!pip -q install " + " ".join(missing)
    print("Missing packages found. Installing with the Colab-style command:")
    print(cmd_text)

    try:
        from IPython import get_ipython  # type: ignore

        ip = get_ipython()
        if ip is not None:
            ip.system("pip -q install " + " ".join(missing))
            return
    except Exception:
        pass

    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing])


ensure_dependencies()

import math
import gc
import random
import textwrap
from collections import Counter
from dataclasses import dataclass
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import requests
import certifi
import urllib3
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
from tqdm.auto import tqdm


FALLBACK_SEQUENCES = [
    "MSRFPLPVLQERIRTDLSRQEVSSGMPVQAARVHEALSSSEGATYLMPWQEKKQSPYLLSFHLATLFNIFQQKMDTGRMLSTIRQAIELLVADLFQHFRGEFPPAERDRLLEYLVSDREGRSAQTPLRELESRRAYVQALQLHSRQVLSLDAMLCYYVQSEGERLVGLAQKIDQQNSLKSNVMSSQSTPPSPQELRRSMPRLAGELRDIVLKQTLRQEYQRM",
    "MPQYDSGEQRFLKNLLESGERPQELIDKAIDIMHRTADDLRGIEFEALFQSQSITQLGSTLLHFTTLLARQLNMPQHLESRQAALELVALDSQHHSMPAQSLRQLEERRAYLQALRLHSEQVLSLDALICYYVQADGQRLVGLAEKIDQQNRLKTNVMSSQSMPASAQELRRSMARLAGELRDIVLKQTLRQEYQRM",
]

AMINO_ACIDS = "ACDEFGHIKLMNPQRSTVWY"
VOCAB = ["<P>", "<B>", "<E>"] + list(AMINO_ACIDS)
PAD_IDX = VOCAB.index("<P>")
BOS_IDX = VOCAB.index("<B>")
EOS_IDX = VOCAB.index("<E>")
CHAR_TO_ID = {char: idx for idx, char in enumerate(VOCAB)}
ID_TO_CHAR = {idx: char for char, idx in CHAR_TO_ID.items()}


@dataclass
class Config:
    download_uniprot: bool = True
    num_sequences: int = 500
    epochs: int = 10
    batch_size: int = 8
    learning_rate: float = 0.0003
    block_size: int = 128
    n_layers: int = 2
    n_heads: int = 4
    n_embed: int = 64
    pair_embed: int = 32
    dropout: float = 0.1
    mixed_precision: bool = True
    candidates: int = 10
    temperature: float = 0.85
    top_k: int = 12
    min_output_length: int = 150
    max_output_length: int = 240
    seed: int = 42


@dataclass
class GeneratedCandidate:
    rank: int
    sequence: str
    score: float
    model_loss: float
    length_penalty: float
    composition_distance: float
    repeat_penalty: float
    duplicate_penalty: float


def ask_int(label: str, default: int, minimum: int | None = None) -> int:
    while True:
        try:
            value = input(f"{label} [{default}]: ").strip()
        except EOFError:
            return default
        if value == "":
            return default
        try:
            parsed = int(value)
            if minimum is not None and parsed < minimum:
                print(f"Use a value >= {minimum}.")
                continue
            return parsed
        except ValueError:
            print("Please enter a whole number.")


def ask_float(label: str, default: float, minimum: float | None = None) -> float:
    while True:
        try:
            value = input(f"{label} [{default}]: ").strip()
        except EOFError:
            return default
        if value == "":
            return default
        try:
            parsed = float(value)
            if minimum is not None and parsed < minimum:
                print(f"Use a value >= {minimum}.")
                continue
            return parsed
        except ValueError:
            print("Please enter a number.")


def ask_bool(label: str, default: bool) -> bool:
    default_text = "y" if default else "n"
    while True:
        try:
            value = input(f"{label} (y/n) [{default_text}]: ").strip().lower()
        except EOFError:
            return default
        if value == "":
            return default
        if value in {"y", "yes", "true", "1"}:
            return True
        if value in {"n", "no", "false", "0"}:
            return False
        print("Please enter y or n.")


def get_config() -> Config:
    print("\n=== Settings ===")
    print("Press Enter to keep a default. Change epochs, batch size, output count, etc. here.\n")

    cfg = Config()
    cfg.download_uniprot = ask_bool("Download LuxR sequences from UniProt", cfg.download_uniprot)
    cfg.num_sequences = ask_int("Max UniProt sequences to train on", cfg.num_sequences, 1)
    cfg.epochs = ask_int("Epochs", cfg.epochs, 1)
    cfg.batch_size = ask_int("Batch size", cfg.batch_size, 1)
    cfg.learning_rate = ask_float("Learning rate", cfg.learning_rate, 0.0)
    cfg.block_size = ask_int("Context/block size", cfg.block_size, 16)
    cfg.n_layers = ask_int("Transformer layers", cfg.n_layers, 1)
    cfg.n_heads = ask_int("Attention heads", cfg.n_heads, 1)
    cfg.n_embed = ask_int("Sequence embedding size", cfg.n_embed, 8)
    cfg.pair_embed = ask_int("Pair embedding size", cfg.pair_embed, 4)
    cfg.dropout = ask_float("Dropout", cfg.dropout, 0.0)
    cfg.mixed_precision = ask_bool("Use CUDA mixed precision to save GPU memory", cfg.mixed_precision)
    cfg.candidates = ask_int("Generated final sequences", cfg.candidates, 1)
    cfg.temperature = ask_float("Sampling temperature", cfg.temperature, 0.01)
    cfg.top_k = ask_int("Top-k sampling", cfg.top_k, 1)
    cfg.min_output_length = ask_int("Minimum generated length", cfg.min_output_length, 1)
    cfg.max_output_length = ask_int("Maximum generated length", cfg.max_output_length, cfg.min_output_length)
    cfg.seed = ask_int("Random seed", cfg.seed, 0)

    if cfg.n_embed % cfg.n_heads != 0:
        fixed = cfg.n_heads * math.ceil(cfg.n_embed / cfg.n_heads)
        print(f"Embedding size must divide by heads. Changing n_embed from {cfg.n_embed} to {fixed}.")
        cfg.n_embed = fixed

    cfg.top_k = min(cfg.top_k, len(VOCAB))
    return cfg


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def fetch_uniprot_sequences(max_sequences: int, use_download: bool) -> list[str]:
    if not use_download:
        print("Skipping UniProt download. Using fallback sequences.")
        return FALLBACK_SEQUENCES

    url = "https://rest.uniprot.org/uniprotkb/search"
    queries = [
        "(gene:luxR OR gene_exact:luxR OR protein_name:LuxR) AND taxonomy_id:2 AND length:[150 TO 300]",
        "(gene:luxR OR protein_name:LuxR OR cc_function:LuxR) AND taxonomy_id:2 AND length:[150 TO 300]",
        "luxR AND taxonomy_id:2 AND length:[150 TO 300]",
    ]
    fields = "accession,id,protein_name,gene_names,organism_name,length,sequence"

    print("\nDownloading LuxR protein sequences from UniProt...")

    session = requests.Session()
    session.headers.update(
        {
            "User-Agent": "luxr-colab-protein-generator/1.1 "
            "(https://colab.research.google.com; educational script)"
        }
    )

    def get_json(params: dict[str, str], allow_insecure_ssl: bool = False) -> dict:
        verify_arg: str | bool = False if allow_insecure_ssl else certifi.where()
        if allow_insecure_ssl:
            urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
        response = session.get(url, params=params, timeout=(15, 90), verify=verify_arg)
        response.raise_for_status()
        return response.json()

    sequences: list[str] = []
    seen: set[str] = set()
    ssl_retry_used = False
    candidate_limit = min(max(max_sequences * 4, 100), 500)

    for query in queries:
        params = {
            "query": query,
            "format": "json",
            "fields": fields,
            "size": str(candidate_limit),
        }

        try:
            data = get_json(params)
        except requests.exceptions.SSLError as exc:
            print(f"SSL verification failed while contacting UniProt: {exc}")
            print("Retrying UniProt once without certificate verification for this download.")
            ssl_retry_used = True
            try:
                data = get_json(params, allow_insecure_ssl=True)
            except Exception as retry_exc:
                print(f"UniProt SSL retry failed: {retry_exc}")
                continue
        except Exception as exc:
            print(f"UniProt query failed: {exc}")
            continue

        added = 0
        for entry in data.get("results", []):
            sequence = entry.get("sequence", {}).get("value", "")
            if sequence and sequence not in seen:
                sequences.append(sequence)
                seen.add(sequence)
                added += 1
            if len(sequences) >= candidate_limit:
                break

        if added:
            print(f"UniProt query returned {added} new sequence candidates: {query}")

        if len(sequences) >= candidate_limit:
            break

    if ssl_retry_used:
        print("Note: SSL fallback was used. In Colab this usually is not needed.")

    valid = set(AMINO_ACIDS)
    clean = [seq for seq in sequences if seq and all(char in valid for char in seq)]
    if not clean:
        print("UniProt returned no clean amino acid sequences. Using fallback sequences.")
        return FALLBACK_SEQUENCES

    diverse: list[str] = []
    for seq in clean:
        is_duplicate = False
        for other in diverse:
            matches = sum(1 for a, b in zip(seq, other) if a == b)
            similarity = matches / max(len(seq), len(other))
            if similarity > 0.90:
                is_duplicate = True
                break
        if not is_duplicate:
            diverse.append(seq)
            if len(diverse) >= max_sequences:
                break

    if not diverse:
        return FALLBACK_SEQUENCES

    print(f"Loaded {len(diverse)} diverse training sequences.")
    return diverse


def encode(sequence: str) -> list[int]:
    return [BOS_IDX] + [CHAR_TO_ID[char] for char in sequence if char in CHAR_TO_ID] + [EOS_IDX]


def decode(token_ids: list[int]) -> str:
    skip = {PAD_IDX, BOS_IDX, EOS_IDX}
    return "".join(ID_TO_CHAR[idx] for idx in token_ids if idx not in skip and idx in ID_TO_CHAR)


class ProteinWindowDataset(Dataset):
    def __init__(self, sequences: list[str], block_size: int):
        self.windows: list[list[int]] = []
        self.block_size = block_size

        stride = max(1, block_size // 3)
        window_len = block_size + 1

        for sequence in sequences:
            tokens = encode(sequence)
            if len(tokens) <= window_len:
                padded = tokens + [PAD_IDX] * (window_len - len(tokens))
                self.windows.append(padded)
                continue

            starts = list(range(0, len(tokens) - block_size, stride))
            last_start = max(0, len(tokens) - window_len)
            if last_start not in starts:
                starts.append(last_start)

            for start in starts:
                window = tokens[start : start + window_len]
                if len(window) == window_len:
                    self.windows.append(window)

        if not self.windows:
            raise ValueError("No training windows were created. Try a smaller block size.")

    def __len__(self) -> int:
        return len(self.windows)

    def __getitem__(self, index: int) -> tuple[torch.Tensor, torch.Tensor]:
        window = torch.tensor(self.windows[index], dtype=torch.long)
        return window[:-1], window[1:]


class EvoBlock(nn.Module):
    def __init__(self, cfg: Config):
        super().__init__()
        self.n_heads = cfg.n_heads
        self.n_embed = cfg.n_embed
        self.head_size = cfg.n_embed // cfg.n_heads

        self.query = nn.Linear(cfg.n_embed, cfg.n_embed, bias=False)
        self.key = nn.Linear(cfg.n_embed, cfg.n_embed, bias=False)
        self.value = nn.Linear(cfg.n_embed, cfg.n_embed, bias=False)
        self.attn_dropout = nn.Dropout(cfg.dropout)
        self.resid_dropout = nn.Dropout(cfg.dropout)

        self.outer_left = nn.Linear(cfg.n_embed, cfg.pair_embed)
        self.outer_right = nn.Linear(cfg.n_embed, cfg.pair_embed)
        self.pair_ff = nn.Sequential(
            nn.Linear(cfg.pair_embed, cfg.pair_embed),
            nn.GELU(),
            nn.Linear(cfg.pair_embed, cfg.pair_embed),
        )
        self.pair_to_bias = nn.Linear(cfg.pair_embed, cfg.n_heads)

        self.seq_ff = nn.Sequential(
            nn.Linear(cfg.n_embed, 2 * cfg.n_embed),
            nn.GELU(),
            nn.Dropout(cfg.dropout),
            nn.Linear(2 * cfg.n_embed, cfg.n_embed),
            nn.Dropout(cfg.dropout),
        )
        self.seq_norm_1 = nn.LayerNorm(cfg.n_embed)
        self.seq_norm_2 = nn.LayerNorm(cfg.n_embed)
        self.pair_norm = nn.LayerNorm(cfg.pair_embed)

    def forward(self, sequence: torch.Tensor, pair: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
        batch, steps, _ = sequence.shape

        left = self.outer_left(sequence)
        right = self.outer_right(sequence)
        pair_update = left[:, :, None, :] * right[:, None, :, :]
        pair = self.pair_norm(pair + self.pair_ff(pair_update))

        normed = self.seq_norm_1(sequence)
        q = self.query(normed).view(batch, steps, self.n_heads, self.head_size).transpose(1, 2)
        k = self.key(normed).view(batch, steps, self.n_heads, self.head_size).transpose(1, 2)
        v = self.value(normed).view(batch, steps, self.n_heads, self.head_size).transpose(1, 2)

        scores = (q @ k.transpose(-2, -1)) / math.sqrt(self.head_size)
        scores = scores + self.pair_to_bias(pair).permute(0, 3, 1, 2)

        causal_mask = torch.tril(torch.ones(steps, steps, device=sequence.device, dtype=torch.bool))
        scores = scores.masked_fill(~causal_mask[None, None, :, :], float("-inf"))

        attn = F.softmax(scores, dim=-1)
        attn = self.attn_dropout(attn)
        update = (attn @ v).transpose(1, 2).contiguous().view(batch, steps, self.n_embed)

        sequence = sequence + self.resid_dropout(update)
        sequence = sequence + self.seq_ff(self.seq_norm_2(sequence))
        return sequence, pair


class ProteinGeneratorModel(nn.Module):
    def __init__(self, cfg: Config):
        super().__init__()
        self.cfg = cfg
        self.token_embedding = nn.Embedding(len(VOCAB), cfg.n_embed)
        self.position_embedding = nn.Embedding(cfg.block_size, cfg.n_embed)
        self.pair_seed = nn.Parameter(torch.randn(1, cfg.block_size, cfg.block_size, cfg.pair_embed) * 0.02)
        self.blocks = nn.ModuleList([EvoBlock(cfg) for _ in range(cfg.n_layers)])
        self.final_norm = nn.LayerNorm(cfg.n_embed)
        self.output_head = nn.Linear(cfg.n_embed, len(VOCAB), bias=False)
        self.output_head.weight = self.token_embedding.weight

    def forward(
        self, input_ids: torch.Tensor, targets: torch.Tensor | None = None
    ) -> tuple[torch.Tensor, torch.Tensor | None]:
        batch, steps = input_ids.shape
        if steps > self.cfg.block_size:
            raise ValueError(f"Input length {steps} exceeds block size {self.cfg.block_size}.")

        token_emb = self.token_embedding(input_ids)
        pos_ids = torch.arange(steps, device=input_ids.device)
        pos_emb = self.position_embedding(pos_ids)
        sequence = token_emb + pos_emb

        pair = self.pair_seed[:, :steps, :steps, :].expand(batch, steps, steps, self.cfg.pair_embed)
        for block in self.blocks:
            sequence, pair = block(sequence, pair)

        logits = self.output_head(self.final_norm(sequence))
        loss = None
        if targets is not None:
            loss = F.cross_entropy(
                logits.reshape(-1, len(VOCAB)),
                targets.reshape(-1),
                ignore_index=PAD_IDX,
            )
        return logits, loss


def make_loaders(dataset: Dataset, cfg: Config) -> tuple[DataLoader, DataLoader | None]:
    if len(dataset) == 1:
        train_dataset = dataset
        val_dataset = None
    else:
        train_size = max(1, int(0.9 * len(dataset)))
        val_size = len(dataset) - train_size
        if val_size == 0:
            train_size -= 1
            val_size = 1
        train_dataset, val_dataset = torch.utils.data.random_split(
            dataset,
            [train_size, val_size],
            generator=torch.Generator().manual_seed(cfg.seed),
        )

    train_loader = DataLoader(
        train_dataset,
        batch_size=min(cfg.batch_size, len(train_dataset)),
        shuffle=True,
        drop_last=False,
    )
    val_loader = None
    if val_dataset is not None and len(val_dataset) > 0:
        val_loader = DataLoader(
            val_dataset,
            batch_size=min(cfg.batch_size, len(val_dataset)),
            shuffle=False,
            drop_last=False,
        )
    return train_loader, val_loader


def clear_cuda_memory() -> None:
    gc.collect()
    if torch.cuda.is_available():
        torch.cuda.empty_cache()
        try:
            torch.cuda.ipc_collect()
        except Exception:
            pass


def is_cuda_oom(exc: BaseException) -> bool:
    text = str(exc).lower()
    return isinstance(exc, RuntimeError) and (
        "cuda out of memory" in text or "outofmemoryerror" in text or "out of memory" in text
    )


def make_grad_scaler(enabled: bool):
    try:
        return torch.amp.GradScaler("cuda", enabled=enabled)
    except Exception:
        return torch.cuda.amp.GradScaler(enabled=enabled)


def autocast_cuda(enabled: bool):
    try:
        return torch.amp.autocast("cuda", enabled=enabled)
    except Exception:
        return torch.cuda.amp.autocast(enabled=enabled)


def train_batch_with_oom_retry(
    model: ProteinGeneratorModel,
    optimizer: torch.optim.Optimizer,
    scaler,
    x: torch.Tensor,
    y: torch.Tensor,
    use_amp: bool,
) -> float:
    micro_batch_size = x.size(0)

    while micro_batch_size >= 1:
        try:
            losses: list[float] = []
            for start in range(0, x.size(0), micro_batch_size):
                xb = x[start : start + micro_batch_size]
                yb = y[start : start + micro_batch_size]

                optimizer.zero_grad(set_to_none=True)
                with autocast_cuda(use_amp):
                    _, loss = model(xb, yb)
                if loss is None:
                    continue

                if use_amp:
                    scaler.scale(loss).backward()
                    scaler.unscale_(optimizer)
                    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                    scaler.step(optimizer)
                    scaler.update()
                else:
                    loss.backward()
                    torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                    optimizer.step()

                losses.append(float(loss.item()))

            if not losses:
                return float("nan")
            return float(np.mean(losses))

        except RuntimeError as exc:
            if not is_cuda_oom(exc):
                raise

            optimizer.zero_grad(set_to_none=True)
            clear_cuda_memory()

            if micro_batch_size == 1:
                raise RuntimeError(
                    "CUDA ran out of memory even at micro-batch size 1. "
                    "Lower Context/block size first, then Pair embedding size, "
                    "Sequence embedding size, or Transformer layers."
                ) from exc

            next_size = max(1, micro_batch_size // 2)
            print(f"\nCUDA OOM on batch size {micro_batch_size}. Retrying with micro-batch size {next_size}.")
            micro_batch_size = next_size

    return float("nan")


def eval_batch_with_oom_retry(
    model: ProteinGeneratorModel,
    x: torch.Tensor,
    y: torch.Tensor,
    use_amp: bool,
) -> float:
    micro_batch_size = x.size(0)

    while micro_batch_size >= 1:
        try:
            losses: list[float] = []
            with torch.no_grad():
                for start in range(0, x.size(0), micro_batch_size):
                    xb = x[start : start + micro_batch_size]
                    yb = y[start : start + micro_batch_size]
                    with autocast_cuda(use_amp):
                        _, loss = model(xb, yb)
                    if loss is not None:
                        losses.append(float(loss.item()))
            if not losses:
                return float("nan")
            return float(np.mean(losses))

        except RuntimeError as exc:
            if not is_cuda_oom(exc):
                raise

            clear_cuda_memory()

            if micro_batch_size == 1:
                raise RuntimeError(
                    "CUDA ran out of memory during validation even at micro-batch size 1. "
                    "Lower Context/block size first, then Pair embedding size, "
                    "Sequence embedding size, or Transformer layers."
                ) from exc

            next_size = max(1, micro_batch_size // 2)
            print(f"\nCUDA OOM during validation on batch size {micro_batch_size}. Retrying with {next_size}.")
            micro_batch_size = next_size

    return float("nan")


def train_model(
    model: ProteinGeneratorModel,
    train_loader: DataLoader,
    val_loader: DataLoader | None,
    cfg: Config,
    device: torch.device,
) -> dict[str, list[float]]:
    optimizer = torch.optim.AdamW(model.parameters(), lr=cfg.learning_rate)
    use_amp = device.type == "cuda" and cfg.mixed_precision
    scaler = make_grad_scaler(use_amp)
    history = {"train": [], "val": []}

    print(f"\nTraining on {len(train_loader.dataset)} windows.")
    if val_loader is not None:
        print(f"Validating on {len(val_loader.dataset)} windows.")
    if use_amp:
        print("CUDA mixed precision is enabled to reduce GPU memory use.")

    for epoch in range(1, cfg.epochs + 1):
        model.train()
        train_losses: list[float] = []
        progress = tqdm(train_loader, desc=f"Epoch {epoch}/{cfg.epochs}", leave=False)
        for x, y in progress:
            x = x.to(device)
            y = y.to(device)

            loss_value = train_batch_with_oom_retry(model, optimizer, scaler, x, y, use_amp)
            if not math.isnan(loss_value):
                train_losses.append(loss_value)
            loss_text = f"{np.mean(train_losses):.4f}" if train_losses else "n/a"
            progress.set_postfix(loss=loss_text)

        model.eval()
        val_losses: list[float] = []
        if val_loader is not None:
            for x, y in val_loader:
                x = x.to(device)
                y = y.to(device)
                loss_value = eval_batch_with_oom_retry(model, x, y, use_amp)
                if not math.isnan(loss_value):
                    val_losses.append(loss_value)

        train_loss = float(np.mean(train_losses)) if train_losses else float("nan")
        val_loss = float(np.mean(val_losses)) if val_losses else float("nan")
        history["train"].append(train_loss)
        history["val"].append(val_loss)

        val_text = f"{val_loss:.4f}" if not math.isnan(val_loss) else "n/a"
        print(f"Epoch {epoch:02d} | Train loss: {train_loss:.4f} | Val loss: {val_text}")

    return history


def plot_loss_bar_graph(history: dict[str, list[float]], output_path: Path) -> None:
    epochs = np.arange(1, len(history["train"]) + 1)
    width = 0.38
    fig_width = max(8, len(epochs) * 0.65)

    plt.figure(figsize=(fig_width, 5.2))
    plt.bar(epochs - width / 2, history["train"], width=width, label="Train loss", color="#2563eb")

    val = np.array(history["val"], dtype=float)
    if not np.all(np.isnan(val)):
        plt.bar(epochs + width / 2, val, width=width, label="Validation loss", color="#f97316")

    plt.title("Training Loss Bar Graph")
    plt.xlabel("Epoch")
    plt.ylabel("Cross-entropy loss")
    plt.xticks(epochs)
    plt.grid(axis="y", alpha=0.25)
    plt.legend()
    plt.tight_layout()
    plt.savefig(output_path, dpi=180)
    print(f"\nSaved bar graph: {output_path.resolve()}")
    plt.show()


def sample_next_token(logits: torch.Tensor, temperature: float, top_k: int) -> int:
    logits = logits.clone()
    logits[PAD_IDX] = float("-inf")
    logits[BOS_IDX] = float("-inf")

    logits = logits / max(temperature, 1e-6)
    if top_k > 0:
        k = min(top_k, logits.numel())
        values, indices = torch.topk(logits, k)
        probs = F.softmax(values, dim=-1)
        choice = torch.multinomial(probs, num_samples=1)
        return int(indices[choice].item())

    probs = F.softmax(logits, dim=-1)
    return int(torch.multinomial(probs, num_samples=1).item())


def generate_sequence(model: ProteinGeneratorModel, cfg: Config, device: torch.device) -> str:
    model.eval()
    token_ids = [BOS_IDX]
    use_amp = device.type == "cuda" and cfg.mixed_precision

    with torch.no_grad():
        while len(token_ids) - 1 < cfg.max_output_length:
            context = token_ids[-cfg.block_size :]
            x = torch.tensor([context], dtype=torch.long, device=device)
            with autocast_cuda(use_amp):
                logits, _ = model(x)
            next_logits = logits[0, -1, :]

            if len(token_ids) - 1 < cfg.min_output_length:
                next_logits = next_logits.clone()
                next_logits[EOS_IDX] = float("-inf")

            next_id = sample_next_token(next_logits, cfg.temperature, cfg.top_k)
            if next_id == EOS_IDX:
                break
            token_ids.append(next_id)

    return decode(token_ids)


def aa_composition(sequence: str) -> str:
    counts = Counter(sequence)
    most_common = counts.most_common(5)
    return ", ".join(f"{aa}:{count}" for aa, count in most_common)


def amino_acid_profile(sequences: list[str]) -> dict[str, float]:
    counts = Counter()
    total = 0
    for sequence in sequences:
        counts.update(char for char in sequence if char in AMINO_ACIDS)
        total += sum(1 for char in sequence if char in AMINO_ACIDS)

    if total == 0:
        return {aa: 1.0 / len(AMINO_ACIDS) for aa in AMINO_ACIDS}

    return {aa: counts[aa] / total for aa in AMINO_ACIDS}


def max_repeat_fraction(sequence: str) -> float:
    if not sequence:
        return 1.0

    longest = 1
    current = 1
    for prev, char in zip(sequence, sequence[1:]):
        if char == prev:
            current += 1
            longest = max(longest, current)
        else:
            current = 1
    return longest / len(sequence)


def sequence_model_loss(
    model: ProteinGeneratorModel,
    sequence: str,
    cfg: Config,
    device: torch.device,
) -> float:
    tokens = encode(sequence)
    if len(tokens) < 2:
        return float("inf")

    weighted_losses: list[float] = []
    token_counts: list[int] = []
    use_amp = device.type == "cuda" and cfg.mixed_precision

    model.eval()
    with torch.no_grad():
        for start in range(0, len(tokens) - 1, cfg.block_size):
            stop = min(start + cfg.block_size, len(tokens) - 1)
            x_ids = tokens[start:stop]
            y_ids = tokens[start + 1 : start + 1 + len(x_ids)]
            if not x_ids or len(x_ids) != len(y_ids):
                continue

            x = torch.tensor([x_ids], dtype=torch.long, device=device)
            y = torch.tensor([y_ids], dtype=torch.long, device=device)
            with autocast_cuda(use_amp):
                logits, _ = model(x)
            loss = F.cross_entropy(logits.reshape(-1, len(VOCAB)), y.reshape(-1))
            weighted_losses.append(float(loss.item()) * len(y_ids))
            token_counts.append(len(y_ids))

    if not token_counts:
        return float("inf")
    return sum(weighted_losses) / sum(token_counts)


def rank_generated_sequences(
    model: ProteinGeneratorModel,
    generated_sequences: list[str],
    training_sequences: list[str],
    cfg: Config,
    device: torch.device,
) -> list[GeneratedCandidate]:
    reference_profile = amino_acid_profile(training_sequences)
    training_lengths = np.array([len(seq) for seq in training_sequences], dtype=float)
    target_length = float(np.mean(training_lengths)) if len(training_lengths) else cfg.max_output_length
    length_spread = float(np.std(training_lengths)) if len(training_lengths) else 1.0
    length_spread = max(length_spread, 1.0)

    ranked: list[tuple[float, GeneratedCandidate]] = []
    seen: set[str] = set()

    for sequence in generated_sequences:
        model_loss = sequence_model_loss(model, sequence, cfg, device)
        length_penalty = abs(len(sequence) - target_length) / length_spread

        profile = amino_acid_profile([sequence])
        composition_distance = sum(abs(profile[aa] - reference_profile[aa]) for aa in AMINO_ACIDS)

        repeat_fraction = max_repeat_fraction(sequence)
        repeat_penalty = max(0.0, repeat_fraction - 0.08)
        duplicate_penalty = 2.0 if sequence in seen else 0.0
        seen.add(sequence)

        rank_loss = (
            model_loss
            + 0.35 * length_penalty
            + 2.50 * composition_distance
            + 4.00 * repeat_penalty
            + duplicate_penalty
        )
        score = 100.0 / (1.0 + rank_loss)

        candidate = GeneratedCandidate(
            rank=0,
            sequence=sequence,
            score=score,
            model_loss=model_loss,
            length_penalty=length_penalty,
            composition_distance=composition_distance,
            repeat_penalty=repeat_penalty,
            duplicate_penalty=duplicate_penalty,
        )
        ranked.append((rank_loss, candidate))

    ranked.sort(key=lambda item: item[0])
    output: list[GeneratedCandidate] = []
    for rank, (_, candidate) in enumerate(ranked, 1):
        output.append(
            GeneratedCandidate(
                rank=rank,
                sequence=candidate.sequence,
                score=candidate.score,
                model_loss=candidate.model_loss,
                length_penalty=candidate.length_penalty,
                composition_distance=candidate.composition_distance,
                repeat_penalty=candidate.repeat_penalty,
                duplicate_penalty=candidate.duplicate_penalty,
            )
        )
    return output


def save_outputs(candidates: list[GeneratedCandidate], output_dir: Path) -> tuple[Path, Path]:
    fasta_path = output_dir / "luxr_generated_sequences.fasta"
    csv_path = output_dir / "luxr_generated_sequences.csv"

    with fasta_path.open("w", encoding="utf-8") as fasta:
        for candidate in candidates:
            sequence = candidate.sequence
            fasta.write(
                f">rank_{candidate.rank}|generated_luxr_{candidate.rank}|"
                f"score={candidate.score:.2f}|model_loss={candidate.model_loss:.4f}|"
                f"length={len(sequence)}\n"
            )
            fasta.write("\n".join(textwrap.wrap(sequence, width=80)) + "\n")

    with csv_path.open("w", encoding="utf-8") as csv:
        csv.write(
            "rank,id,score,model_loss,length,length_penalty,"
            "composition_distance,repeat_penalty,duplicate_penalty,sequence\n"
        )
        for candidate in candidates:
            sequence = candidate.sequence
            csv.write(
                f"{candidate.rank},generated_luxr_{candidate.rank},"
                f"{candidate.score:.4f},{candidate.model_loss:.6f},{len(sequence)},"
                f"{candidate.length_penalty:.6f},{candidate.composition_distance:.6f},"
                f"{candidate.repeat_penalty:.6f},{candidate.duplicate_penalty:.6f},{sequence}\n"
            )

    return fasta_path, csv_path


def print_final_sequences(candidates: list[GeneratedCandidate]) -> None:
    print("\n=== FINAL RECOMMENDED OUTPUT: BEST TO LOWEST ===")
    for candidate in candidates:
        sequence = candidate.sequence
        print(
            f"\n>rank_{candidate.rank} | score={candidate.score:.2f} | "
            f"model_loss={candidate.model_loss:.4f} | length={len(sequence)} | "
            f"top amino acids: {aa_composition(sequence)}"
        )
        print("\n".join(textwrap.wrap(sequence, width=80)))


def main() -> None:
    cfg = get_config()
    set_seed(cfg.seed)
    clear_cuda_memory()

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\nEngine bound to: {device}")

    sequences = fetch_uniprot_sequences(cfg.num_sequences, cfg.download_uniprot)
    dataset = ProteinWindowDataset(sequences, cfg.block_size)
    train_loader, val_loader = make_loaders(dataset, cfg)

    try:
        model = ProteinGeneratorModel(cfg).to(device)
    except RuntimeError as exc:
        if device.type != "cuda" or not is_cuda_oom(exc):
            raise
        print("\nCUDA ran out of memory while creating the model.")
        print("Switching this run to CPU. For a faster GPU run, lower block size or model size.")
        clear_cuda_memory()
        device = torch.device("cpu")
        cfg.mixed_precision = False
        model = ProteinGeneratorModel(cfg).to(device)

    total_params = sum(param.numel() for param in model.parameters())
    print(f"Model parameters: {total_params:,}")

    try:
        history = train_model(model, train_loader, val_loader, cfg, device)
    except RuntimeError as exc:
        if device.type != "cuda" or not is_cuda_oom(exc):
            raise
        print("\nGPU memory was still not enough, even after automatic micro-batch retries.")
        print("Switching this run to CPU so it can finish.")
        print("For a faster GPU run, lower Context/block size first, then Pair embedding size,")
        print("Sequence embedding size, Transformer layers, or Batch size.")
        model = model.to("cpu")
        clear_cuda_memory()
        device = torch.device("cpu")
        cfg.mixed_precision = False
        history = train_model(model, train_loader, val_loader, cfg, device)

    graph_path = Path("luxr_training_loss_bar_graph.png")
    plot_loss_bar_graph(history, graph_path)

    print("\nGenerating final protein sequences...")
    generated = [generate_sequence(model, cfg, device) for _ in range(cfg.candidates)]
    ranked_candidates = rank_generated_sequences(model, generated, sequences, cfg, device)
    print_final_sequences(ranked_candidates)

    fasta_path, csv_path = save_outputs(ranked_candidates, Path("."))
    print("\nSaved final outputs:")
    print(f"FASTA: {fasta_path.resolve()}")
    print(f"CSV:   {csv_path.resolve()}")
    print(f"Graph: {graph_path.resolve()}")


if __name__ == "__main__":
    main()